# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
  - title: '🚀 Features'
    labels: 
      - 'feature'  # 配列形式で指定
  - title: '🐛 Bug Fixes'
    labels: 
      - 'bug'  # 配列形式で指定
  - title: '🔧 Enhancements'
    labels: 
      - 'enhancement'  # 配列形式で指定
  - title: '📚 Documentation'
    labels: 
      - 'documentation'  # 配列形式で指定
  - title: '⚡ Performance Improvements'
    labels: 
      - 'performance'  # 配列形式で指定
  - title: '⚠️ Deprecation'
    labels: 
      - 'deprecate'  # 配列形式で指定
  - title: '🎨 Style Changes'
    labels: 
      - 'style'  # 配列形式で指定
  - title: '🔗 Dependency Updates'
    labels: 
      - 'dependency'  # 配列形式で指定
